[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "llm_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.5.1,<3"
fairscale = ">=0.4.6,<0.5"
fire = ">=0.7.0,<0.8"
tiktoken = "==0.4.0"
blobfile = ">=3.0.0,<4"
transformers = ">=4.46.3,<5"
